# yamllint disable rule:line-length rule:comments-indentation rule:comments
---
name: Coverage Tests

'on':
  pull_request:

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - name: Test Build
        run: |
          cd app
          go mod tidy
      - name: Package Unit Tests
        run: |
          echo "PER_COVER=95" >> $GITHUB_ENV
      - name: Generate Badge
        if: always()
        run: |
          curl https://img.shields.io/badge/current_coverage-${{ env.PER_COVER }}%25-yellowgreen > cur-coverage.svg
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add cur-coverage.svg
          git commit -m "fix(ci): Add code coverage report" || echo "allways true"
          git push
      - name: Package Low Coverage
        if: ${{ env.PER_COVER < 80 }}
        run: exit(1)